from io import StringIO
from Bio import SeqIO

verified_CvaB = """
>AAL08400.1 MceG [Klebsiella pneumoniae RYC492]
MSNGNVRRMINQLDMRWRRRVPVIHQTETSECGLACLAMICGHFGKNIDLISLRRKFNLS
ARGANLAGINSIAEQLGMVTRALSLELDELGALKTPCILHWDFSHFVVLVSVKRNRYVLH
DPARGRRNVGLEEMTRYFTGVALEVWPGSEFSEETTQNRIQLRSLINSIYGIKSTLAKIF
CLSVVIEAINLVMPVGTQLVMDHAIPAGDRGLLTLISAGLMFFILLRAATGMLRAWSSLV
MGTLINVQWQSGLFNHLLRLPLAYFERRKLGDIQSRFGSLDTLRATFTTSVVGAIMDSIM
VVGVFVMMLLYGGYLTWIVLGFTTVYVLIRLVTYGYYRQISEETLVRGARASSYFMETLY
GIATVKIQGMAERRGTHWLNLKIDAINSGIKLTKMDLFFGGINTFVAACDQVAILWLGTS
LVIDNQMTIGMFVAFGSFRGQFSDRVASLTNFLLQLRMMSLHNERIADIALHEKEEKKPE
LDIVADMTPVSLETTDLSYRYDSQSAPVFSGLYLSVTPGESVAITGTSGAGKTTLMKVLC
GLFEPDSGKVLVNGTDIRQLGINNYHRMIACVMQDDRLFSGSIRENICGFSEEMDEAWMI
ECARASYIHDVIMKMPMGYETLIGELGEGLSGGQKQRIFIARALYRRPGILFMDEATSSL
DTESERFVNVAIRNMNITRVIIAHRETTLRTVDRTISI
>CAJ44959.1 MchF protein [Escherichia coli]
MTNGSFRQIINQLDMRWRRRVPVIHQTETAECGLACLAMICGHFGKNIDLISLRRKFNLS
ARGANLAGINGIAEQLGMVTRALSLELDELGALKMPCILHWDFSHFVVLVSVKRNRYVLH
DPARGRRYLGREEMSRYFTGIALEVWPGSEFLAETQQIRISLRSLINSIYGIKRTLAKIF
CLSVVIEAINLVMPVGTQLVMDHAIPAGDRGLLTLISAGLMFFILLRAAVSMLRAWSSLV
MSTLINIQWQSGLFNHLLRLPLAFFERRKLGDIQSRFGSLDTLRATFTTCVVGAIMDSIM
VVGVFVMMLLYGGYLTWIVLGFTMVYVLIRLVTYGYYRQISEETLVRGARASSYFMESLY
GIATVKIQGMAGIRGTHWLNLKIDAINSGIKLTKMDLLFGGINTFVAACDQVAILWLGAS
LVIDNQMTIGMFVAFGSFRGQFSDRVASLTSFLLQLRIMSLHNERIADIALHEKEEKKPE
IEIVADMSPVSLETTDLSYRYDSQSAQVFSGLNLSVAPGESVAITGASGAGKTTLMKVLC
GLFEPDSGKVLVNGTDIRQLGINNYHRMIACVMQDDRLFSGSIRENICGFAEETDDEWMT
ECARASHIHDVIMKMPMGYETLIGELGEGLSGGQKQRIFIARALYRKPGILFMDEATSSL
DTESERFVNAAIKKMNITRVIIAHRETTLRTVDRIISI
>AAP03990.1 putative microcin L transport protein [Escherichia coli]
MTNGNFRQIINQLDMRWRRRVPVIHQTETAECGLACLAMICGHFGKNIDLISLRRKFNLS
ARGANLAGINGIAEQLGMVTRALSLELDELGALKMPCILHWDFSHFVVLVSVKRNRYVLH
DPARGRRYLGREEMSRYFTGIALEVWPGSEFQAETQQTRISLRSLINSIYGIKRTLAKIF
CLSVVIEAINLVMPVGTQLVMDHAIPAGDRGLLTLISAGLMFFILLRAAVSMLRAWSSLV
MSTLINVQWQSGLFDHLLRLPLAFFERRKLGDIQSRFDSLDTLRATFTTSVIGLIMDSIM
VVGVFVMMLLYGGYLTWIVLCFTTIYIFIRLVTYGNYRQISEECLVREARAASYFMETLY
GIATVKIQGMVGIRGAYWLNMKIDAINSGIKLTRMDLLFGGINTFVTACDQVVILWLGAG
LVIDNQMTIGMFVAFSSFRGQFSERVTSLTSFLLQLKIMSLHNERIADIALHEKEEKKHE
IEIVAHMGPISLETNDLSYRYDSQSAPIFSALSLSVAPGESVAITGASGAGKTTLMKVLC
GLFEPDSGRVLINGIDIRQMGINNYHRMIACVMQDDRLFSGSIRENICGFAEEMDEEWMV
ECARASHIHDVIMNMPMGYETLIGELGEGLSGGQKQRIFIARALYRKPGILFMDEATSAL
DSESEHFVNVAIKNMNITRVIIAHRETTLKTVDRVISI
>ACP43452.1 McnB [Escherichia coli]
MNNNATSPLNTLLNKLEIGLRRRIPVVHQTESSECGLACLSMICGHYGRHIDLSTLRRQF
NLSALGTTLAGITEIGSQLGMETRAFSLDLNELSVLKLPCILHWEFSHFVVLVSVRKNHF
VLHDPARGRRTVGLAEMSQCFTGVALEVWPGTEFVQETMKNRVVLRTLFRSIYGLRSTLT
KIFCFSLVIEAVGLVIPVGTQLVMDHAIPAGDRGLLSLICVGLMFFILLRTAVSMIRSWS
SLVMETLINVQWQSGLHRHLLQLPLAYFERRKMGDIQSRFSSLDTLRTTFTTSVVGAIMD
SIMVSGVLAMLVLYGGWLTTIVLGFTIIYVLIRLLTYNYYRQLSEESLIREARASSYFME
TLYGIATIKMQGMGERRGRHWLNLKIDAINTGIRLARMDMLFSGINTFVAACDQVVILWL
GTSLVIDNQMTIGMFVAFGVFRGQFSDRVGSLTNFLLQLRMMSLHNERIADIAMNEREAR
KPDTAMKADMYPVALETQDLSFRYDSQSAPVFSNLNISIKPGESVAITGASGSGKTTLMK
VLCGLLVPESGRVMIDGTDIRSLGVNNYHKIISCVMQDDRLFSGSIRENICGFTENIDEA
WMVECARASFIHDVIIKMPMGYDTLIGELGEGLSGGQKQRIFIARALYRRPGILFMDEAT
SALDTESEYYVNQAIKQLNITRIIIAHRETTVKSADRIILLEAPARI
>AFN88378.1 hlyB-like ABC transporter-like protein (plasmid) [Escherichia coli]
MESINWKVRKQLPVIRQTESAECGLACLAMIACWHGLKTDLSTLRERFNIGIQGMTLQRL
IECAASIHLSSRAVRLEPEDLRCLNLPSILHWDMNHFVVLHKVRGNRLYIHDPDRGKITI
SLLDAGKHFTGVALELTPASDFTPRNERKKIHLRQLTGKTPGLLASMTKIIIFALALEIL
ALGGPLLNQLVIDEVLVAADRSLLYVIIVALLLLSLIQLLLSLARQWATISLSVNFNMQW
TARVFHHLVRLPLAWFDARSKGSINARFEAVDIIQQALTTQVLEGILDMLLIVTALCMML
LYSPGMTLIAVIAAIIYGALRALWYPALRQSVEDVWDAGTKESGHFLETLNGIQSLRING
VTIHREAAWLNLNVTRRNTQLRQNRLQMSYELTHTLTESVVSAIILWQGAVEVLDGTFTV
GMLVAYLSYQMRFSSSISNLTDNFFSWRMLDVYNERLADIVLTPQEGHQNQHHWANHNET
ISASQYREHKYDNTHPPLLIEKITFSHKGADKPILDNASLMLFPGEILAITGKSGCGKST
LVKLILGIHTPSEGRINAFGIPHTHSDYFQVRQRIGTVLQDDYLFKGSIADNIMFFSEIR
DHEHMRKCASLALIDSDIMAMPMGYQTLLGETGGGLSGGQKQRILLARALYKKPGLLLLD
EATSHLDVESEIEISQTLRQLGIPVLLIAHRPETIASADRVLYLRDGHFSEITYRPARTH
NINNHPNRR
>AFH37355.1 ABC transporter (plasmid) [Escherichia coli]
MDTLKWTGRKQLPLIRQTESAECGLACLVMMACWHGLQTDLPTLRERFSISTQGMTLQRL
IECAAGIRLSSRAVRLEPEDLKSLSLPCILHWNMNHFVVLYKVRGSRLVIHDPDKGKITL
SLQDAGKHFTGVALELTPASDFTARDERKKIRLRQLTGRTPGLLAAMSRIIIFALALEIL
TLSSPLLNQLVIDEVLVAADRSLLTVIIIALLLLSMTQMLLSLARQWASITLSVNFNMQW
TARVFHHLVRLPLGWFDARSKGSINARFEAVDTIQEALTTQVLEGILDVLLVITALCMML
LYSPEMTLIAVLAAIIYGVLRALWYPSLRQSAEDAWDAGARESGHFLETLNGILSLRING
VTAHREAAWLNLNIVRRNTQLRQSRQLMCYDIAHTLTGSVVSAIILWKGAGEVLNGTFTV
GMLVAYLSYQMRFSSSISSLTDKYFSWRMLDIYNERLADIVLTPTEDYQQQPAQEDNDTS
VFPSVFRGDVADGARVPLSLEHITFSHKGGNKPILRGVSLTLHPGEVMAITGQSGCGKST
LVKLILGIHIPDEGTIRAFGIPHTHPDYFQVRQRIGTVLQDDHLFRGSIADNIIFFSGDR
NHERMIQCARLALIDSDIMSMPMGYQTLIGETGGGLSGGQKQRILLARALYKKPGFLLLD
EATSHLDVESEIQISQTLRQLGLPVLLIAHRPETIASADRVLYLADGCFMELRHKRTIDD
GLNKN
>P22520.1 RecName: Full=Colicin V secretion/processing ATP-binding protein CvaB
MTNRNFRQIINLLDLRWQRRVPVIHQTETAECGLACLAMICGHFGKNIDLIYLRRKFNLS
ARGATLAGINGIAEQLGMATRALSLELDELRVLKTPCILHWDFSHFVVLVSVKRNRYVLH
DPARGIRYISREEMSRYFTGVALEVWPGSEFQSETLQTRISLRSLINSIYGIKRTLAKIF
CLSVVIEAINLLMPVGTQLVMDHAIPAGDRGLLTLISAALMFFILLKAATSTLRAWSSLV
MSTLINVQWQSGLFDHLLRLPLAFFERRKLGDIQSRFDSLDTLRATFTTSVIGFIMDSIM
VVGVCVMMLLYGGYLTWIVLCFTTIYIFIRLVTYGNYRQISEECLVREARAASYFMETLY
GIATVKIQGMVGIRGAHWLNMKIDAINSGIKLTRMDLLFGGINTFVTACDQIVILWLGAG
LVIDNQMTIGMFVAFSSFRGQFSERVASLTSFLLQLRIMSLHNERIADIALHEKEEKKPE
IEIVADMGPISLETNGLSYRYDSQSAPIFSALSLSVAPGESVAITGASGAGKTTLMKVLC
GLFEPDSGRVLINGIDIRQIGINNYHRMIACVMQDDRLFSGSIRENICGFAEEMDEEWMV
ECARASHIHDVIMNMPMGYETLIGELGEGLSGGQKQRIFIARALYRKPGILFMDEATSAL
DSESEHFVNVAIKNMNITRVIIAHRETTLRTVDRVISI

"""

verified_CvaB_SeqIO = SeqIO.parse(StringIO(verified_CvaB), "fasta")
with open("verified_CvaB.pep","w") as seq_out:
  SeqIO.write(verified_CvaB_SeqIO, seq_out,"fasta")


SAMPLES, = glob_wildcards("{sample}_cinfulOut/")


rule final:
	input:
		expand("{sample}_cinfulOut/duomolog_CvaB/summary_out.txt", sample = SAMPLES)




# rule filter_input:
# 	input:
# 		"input_seqs.fa"
# 	output:
# 		"input_seqs.short.fa"
# 	shell:
# 		"seqkit fx2tab -l {input} | awk '$3 < 150' > {output}"

rule makeblastdb:
	input:
		"verified_CvaB.pep"
	output:
		"verified_CvaB.pep.phr"		
	shell:
		"makeblastdb -dbtype prot -in {input}"

rule blast:
	input:
		verified_CvaB = "verified_CvaB.pep",
		blastdb = "verified_CvaB.pep.phr",
		input_seqs = "{sample}_cinfulOut/{sample}.faa"
	output:
		"{sample}_cinfulOut/{sample}.verified_CvaB.blast.txt"
	shell:
		"blastp -db {input.verified_CvaB} -query {input.input_seqs} -outfmt 6 -out {output} -evalue 0.001 -max_target_seqs 1"
		


rule verified_CvaBMSA:
	input:
		"verified_CvaB.pep"
	output:
		"verified_CvaB.aln"
	shell:
		"mafft --auto {input} > {output}"
		
rule buildhmm:
	input:
		"verified_CvaB.aln"
	output:
		"verified_CvaB.hmm"
	shell:
		"hmmbuild {output} {input}"

rule duomolog:
	input:
		verified_CvaB = "verified_CvaB.pep",
		input_seqs = "{sample}_cinfulOut/{sample}.faa",
		blastout = "{sample}_cinfulOut/{sample}.verified_CvaB.blast.txt",
		hmm = "verified_CvaB.hmm"
	output:
		"{sample}_cinfulOut/duomolog_CvaB/summary_out.txt"
	shell:
		"""duomolog blast_v_hmmer --inFile {input.verified_CvaB} --queryFile {input.input_seqs} \
			--blastFile {input.blastout} \
			--intersectOnly \
			--hmmFile {input.hmm}	\
			--summaryOut {output}
		"""

# rule getBestHits:
# 	input:
# 		blast_hits = "verified_CvaB.blast.txt",
# 		hmmer_hits = "verified_CvaB.hmmerOut.txt",
# 		seq = "input_seqs.short.fa"
# 	output:
# 		"verified_CvaB.bestHits.fa"
# 	shell:
# 		"touch {output}"

# rule bestHitsMSA:
# 	input:
# 		"verified_CvaB.bestHits.fa"
# 	output:
# 		"verified_CvaB.bestHits.aln"
# 	shell:
# 		"touch {output}"

# rule evaluateMSA:
# 	input:
# 		"verified_CvaB.bestHits.aln"
# 	output:
# 		"verified_CvaB.evaluateMSA.txt"

# rule catalytic_triad:
# 	input:
# 		"verified_CvaB.evaluateMSA.txt"
# 	output:
# 		"verified_CvaB.catalytic_triad.txt"


# rule putative_CvaB:
# 	input:
# 		seqs = "verified_CvaB.bestHits.fa",
# 		evaluateMSA = "verified_CvaB.evaluateMSA.txt",
# 		catalytic_triad = "verified_CvaB.catalytic_triad.txt"

# 	output:
# 		"putative_CvaB.txt"